/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminTopicsTopicIdRouteImport } from './routes/admin.topics.$topicId'
import { Route as AdminNotesNoteIdRouteImport } from './routes/admin.notes.$noteId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminTopicsTopicIdRoute = AdminTopicsTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => AdminTopicsRoute,
} as any)
const AdminNotesNoteIdRoute = AdminNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AdminNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/notes/$noteId': typeof AdminNotesNoteIdRoute
  '/admin/topics/$topicId': typeof AdminTopicsTopicIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/notes/$noteId': typeof AdminNotesNoteIdRoute
  '/admin/topics/$topicId': typeof AdminTopicsTopicIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/notes/$noteId': typeof AdminNotesNoteIdRoute
  '/admin/topics/$topicId': typeof AdminTopicsTopicIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/'
    | '/admin/notes/$noteId'
    | '/admin/topics/$topicId'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/topics'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/admin/notes/$noteId'
    | '/admin/topics/$topicId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/topics'
    | '/admin/users'
    | '/_public/'
    | '/admin/'
    | '/admin/notes/$noteId'
    | '/admin/topics/$topicId'
    | '/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/topics/$topicId': {
      id: '/admin/topics/$topicId'
      path: '/$topicId'
      fullPath: '/admin/topics/$topicId'
      preLoaderRoute: typeof AdminTopicsTopicIdRouteImport
      parentRoute: typeof AdminTopicsRoute
    }
    '/admin/notes/$noteId': {
      id: '/admin/notes/$noteId'
      path: '/$noteId'
      fullPath: '/admin/notes/$noteId'
      preLoaderRoute: typeof AdminNotesNoteIdRouteImport
      parentRoute: typeof AdminNotesRoute
    }
  }
}

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminNotesRouteChildren {
  AdminNotesNoteIdRoute: typeof AdminNotesNoteIdRoute
}

const AdminNotesRouteChildren: AdminNotesRouteChildren = {
  AdminNotesNoteIdRoute: AdminNotesNoteIdRoute,
}

const AdminNotesRouteWithChildren = AdminNotesRoute._addFileChildren(
  AdminNotesRouteChildren,
)

interface AdminTopicsRouteChildren {
  AdminTopicsTopicIdRoute: typeof AdminTopicsTopicIdRoute
}

const AdminTopicsRouteChildren: AdminTopicsRouteChildren = {
  AdminTopicsTopicIdRoute: AdminTopicsTopicIdRoute,
}

const AdminTopicsRouteWithChildren = AdminTopicsRoute._addFileChildren(
  AdminTopicsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminNotesRoute: typeof AdminNotesRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTopicsRoute: typeof AdminTopicsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNotesRoute: AdminNotesRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTopicsRoute: AdminTopicsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
