import { StyleSheet } from "react-native";

export const mediaPickerStyles = StyleSheet.create({
	root: { backgroundColor: "#090909", flex: 1 },
	header: {
		alignItems: "center",
		flexDirection: "row",
		height: 58,
		justifyContent: "space-between",
		paddingHorizontal: 16,
	},
	doneButton: {
		alignItems: "center",
		borderRadius: 18,
		minWidth: 66,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	doneButtonDisabled: { backgroundColor: "#363636" },
	doneText: { color: "#111", fontSize: 13, fontWeight: "700" },
	permissionBanner: {
		alignItems: "center",
		backgroundColor: "#111",
		flexDirection: "row",
		gap: 8,
		minHeight: 48,
		paddingHorizontal: 14,
	},
	permissionBannerText: { color: "#c7c7c7", flex: 1, fontSize: 13 },
	permissionMessage: {
		alignItems: "center",
		gap: 8,
		paddingHorizontal: 40,
		paddingTop: 62,
	},
	permissionMessageTitle: { color: "#fff", fontSize: 17, fontWeight: "700" },
	permissionMessageText: {
		color: "#888",
		fontSize: 14,
		lineHeight: 21,
		textAlign: "center",
	},
	gridArea: { flex: 1 },
	centered: { alignItems: "center", flex: 1, justifyContent: "center" },
	loadingMore: { alignItems: "center", paddingVertical: 18, width: "100%" },
	emptyText: { color: "#777", paddingTop: 60, textAlign: "center" },
	addMoreTile: {
		alignItems: "center",
		backgroundColor: "#242424",
		justifyContent: "center",
	},
	addMoreText: { color: "#919191", fontSize: 12, lineHeight: 16 },
	selectedOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.25)",
	},
	selectionBadge: {
		borderColor: "rgba(255,255,255,0.9)",
		borderRadius: 12,
		borderWidth: 2,
		height: 24,
		position: "absolute",
		right: 7,
		top: 7,
		width: 24,
	},
	selectionBadgeSelected: { alignItems: "center", justifyContent: "center" },
	selectionNumber: { color: "#101010", fontSize: 12, fontWeight: "800" },
	cameraLabel: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.55)",
		borderRadius: 10,
		bottom: 6,
		height: 20,
		justifyContent: "center",
		left: 6,
		width: 20,
	},
	tabs: {
		alignItems: "flex-start",
		backgroundColor: "#090909",
		flexDirection: "row",
		gap: 46,
		height: 76,
		justifyContent: "center",
		paddingTop: 12,
	},
	tab: { alignItems: "center", minWidth: 48 },
	tabText: { color: "#888", fontSize: 16, fontWeight: "600" },
	tabTextActive: { color: "#fff", fontWeight: "800" },
	tabIndicator: { borderRadius: 3, height: 4, marginTop: 7, width: 24 },
	albumPickerRoot: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.48)",
		justifyContent: "flex-end",
	},
	albumPickerCard: {
		backgroundColor: "#1a1a1a",
		borderTopLeftRadius: 22,
		borderTopRightRadius: 22,
		maxHeight: "72%",
		minHeight: 260,
		paddingHorizontal: 18,
	},
	albumPickerHandle: {
		alignSelf: "center",
		backgroundColor: "#555",
		borderRadius: 2,
		height: 4,
		marginTop: 10,
		width: 38,
	},
	albumPickerTitle: {
		color: "#fff",
		fontSize: 18,
		fontWeight: "700",
		paddingVertical: 18,
	},
	albumRow: {
		alignItems: "center",
		borderBottomColor: "#303030",
		borderBottomWidth: StyleSheet.hairlineWidth,
		flexDirection: "row",
		justifyContent: "space-between",
		minHeight: 62,
	},
	albumRowTitle: { color: "#fff", fontSize: 16, fontWeight: "600" },
	albumRowCount: { color: "#888", fontSize: 12, marginTop: 3 },
	cameraRoot: { backgroundColor: "#000", flex: 1 },
	cameraPermission: {
		alignItems: "center",
		backgroundColor: "#090909",
		flex: 1,
		gap: 12,
		justifyContent: "center",
		paddingHorizontal: 36,
	},
	cameraBack: { left: 16, position: "absolute", top: 14 },
	cameraPermissionTitle: { color: "#fff", fontSize: 19, fontWeight: "700" },
	cameraPermissionText: {
		color: "#999",
		fontSize: 14,
		lineHeight: 21,
		textAlign: "center",
	},
	permissionButton: {
		borderRadius: 20,
		marginTop: 8,
		paddingHorizontal: 22,
		paddingVertical: 11,
	},
	permissionButtonText: { color: "#111", fontSize: 15, fontWeight: "700" },
	cameraTop: {
		flexDirection: "row",
		justifyContent: "space-between",
		left: 16,
		position: "absolute",
		right: 16,
		top: 0,
	},
	roundIconButton: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.42)",
		borderRadius: 24,
		height: 46,
		justifyContent: "center",
		width: 46,
	},
	flashLabel: {
		bottom: 5,
		color: "#fff",
		fontSize: 8,
		fontWeight: "800",
		position: "absolute",
	},
	cameraControls: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.18)",
		bottom: 0,
		flexDirection: "row",
		justifyContent: "space-around",
		left: 0,
		paddingTop: 24,
		position: "absolute",
		right: 0,
	},
	cameraControlSpacer: { width: 48 },
	shutterOuter: {
		alignItems: "center",
		borderColor: "#fff",
		borderRadius: 39,
		borderWidth: 4,
		height: 78,
		justifyContent: "center",
		width: 78,
	},
	shutterInner: {
		backgroundColor: "#fff",
		borderRadius: 31,
		height: 62,
		width: 62,
	},
	flipButton: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.35)",
		borderRadius: 24,
		height: 48,
		justifyContent: "center",
		width: 48,
	},
	previewActions: {
		bottom: 0,
		flexDirection: "row",
		justifyContent: "space-between",
		left: 24,
		position: "absolute",
		right: 24,
	},
	previewButton: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.58)",
		borderRadius: 23,
		minWidth: 96,
		paddingHorizontal: 20,
		paddingVertical: 13,
	},
	previewButtonPrimary: {},
	previewButtonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
	previewButtonPrimaryText: { color: "#111" },
});
